FROM       jamesnesbitt/wunder-kitematic
MAINTAINER james.nesbitt@wunderkraut.com

# More Project related Volumes
VOLUME /app/source
VOLUME /app/assets
VOLUME /app/backup

# optional volume mounts for application functionality
VOLUME /app/.platformsh
VOLUME /app/.drush
VOLUME /app/.ssh

WORKDIR /app
