FROM       jamesnesbitt/wunder-kitematic
MAINTAINER james.nesbitt@wunderkraut.com

# optional volume mounts for application functionality
VOLUME /app/.platformsh
VOLUME /app/.drush
VOLUME /app/.ssh

WORKDIR /app
