FROM       jamesnesbitt/wunder-lampstackplusdev
MAINTAINER james.nesbitt@wunderkraut.com

# Volume for the web-root
VOLUME /app/www

# Expose some ports
EXPOSE 80
EXPOSE 443
EXPOSE 3306

# Set the workdir
WORKDIR /app
